name: "Send Monthly Update"
on:
  schedule:
  # 9:00 am est on every 20 of each month
  - cron: "00 14 20 * *" # UTC

#   ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6)
# * * * * *

jobs:
  calendar_and_social_action:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Notify of next month summary
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/New_York"

      - name: Generate Monthly Update
        uses: ./.github/actions/monthly-update
        id: Monthly-Update

      - name: Send Calendar Invite to RR Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Monthly Update
          to: RoosterRidgeOfficial@gmail.com
          from: Bluegrass Bot # <user@example.com>
          body: ${{ steps.Monthly-Update.outputs.update_message }}
          ignore_cert: true
          convert_markdown: true
          priority: low
